apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-app
spec:
  selector:
    matchLabels:
      app: money-app
  template:
    metadata:
      labels:
        app: money-app
    spec:
      containers:
      - name: money-app
        image: mohamd556/money_app
        resources: {}
        ports:
        - containerPort: 5000
        env:
        - name: API_HOST
          value: "money-api"
        - name: API_PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: money-app
spec:
  type: NodePort
  selector:
    app: money-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30060

